[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "skyledger_ai"
version = "0.1.0"
description = "SkyLedger-AI backend"
authors = [{name = "Syed"}]

[tool.setuptools]
packages = ["app"]
